# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [2]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [5]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [6]:
x = data[feature_cols]
y = data["Sales"]

In [11]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 2, step=1)
selector = selector.fit(x,y)

In [12]:
selector

RFE(estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
                  gamma='scale', kernel='linear', max_iter=-1, shrinking=True,
                  tol=0.001, verbose=False),
    n_features_to_select=2, step=1, verbose=0)

In [13]:
selector.support_

array([ True,  True, False])

In [14]:
selector.ranking_

array([1, 1, 2])

In [16]:
from sklearn.linear_model import LinearRegression

In [18]:
x_pred = x[["TV", "Radio"]]

In [19]:
lm = LinearRegression()
lm.fit(x_pred,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
lm.intercept_

2.921099912405138

In [21]:
lm.coef_

array([0.04575482, 0.18799423])

In [23]:
lm.score(x_pred,y)

0.8971942610828956